services:
  rating-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      FEATURE_FLAG: "true"
      API_ENDPOINT: "https://api/${api.version}/forums.com"
      MONGODB_URI: "mongodb+srv://${MONGODB_USER}:${MONGODB_PASSWORD}@deliverusadvanced.sot48mx.mongodb.net/?retryWrites=true&w=majority&appName=deliverusadvanced"

#    env_file:
#      - .env  # Opcional: Usar un archivo .env para manejar las variables de entorno (como MONGODB_USER y MONGODB_PASSWORD)