apiVersion: apps/v1
kind: Deployment
metadata:
  name: forum-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: forum-service
  template:
    metadata:
      labels:
        app: forum-service
    spec:
      containers:
        - name: forum-service
          image: martirl11/forum-service:v1
          ports:
            - containerPort: 8080

          env:
            - name: FEATURE_FLAG
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: FEATURE_FLAG
            - name: API_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: API_ENDPOINT
            - name: API_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: API_ENDPOINT
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret 
                  key: MONGODB_USER 
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret  
                  key: MONGODB_PASSWORD 
            - name: SENSITIVE_ENV
              valueFrom:
               secretKeyRef:
                 name: my-secret
                 key: sensitive-key
