FROM openjdk:17-jdk-slim

WORKDIR /app

COPY target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java","-jar","app.jar"]


# docker build -t message-service -f ./DockerFile .
# docker run -p 8080:8080 message-service